### ISSUE TITLE
Errors in wscript

### ISSUE THREAD

**Issue by Gaspartame** [ita1024/semantik#77]
When trying to compile semantik-1.0.0, by running `./waf configure build` I faced two errors.

First, the script try to access some libraries in "/home/gaspar/anaconda3/bin/lib", while they are located (by the automatic install script from anaconda) in "/home/gaspar/anaconda3/lib", giving the following error :
> FileNotFoundError: [Errno 2] No such file or directory: '/home/gaspar/anaconda3/bin/lib'

I got around this error by adding a link to the folder.

Second, the script can't find **Qt5WebEngineWidgets**, giving the following error : 
> Could not find Qt5WebEngineWidgets - check `pkg-config --libs Qt5WebEngineWidgets`
> (complete log in /home/gaspar/Desktop/semantik-1.0.0/build/config.log)

The `pkg-config --libs Qt5WebEngineWidgets` command gives :
> -lQt5WebEngineWidgets -lQt5WebEngineCore -lQt5WebChannel -lQt5Positioning -lQt5Quick -lQt5Qml -lQt5Network -lQt5PrintSupport -lQt5Widgets -lQt5Gui -lQt5Core

I also join the ./build/config.log :
[config.log](https://github.com/ita1024/semantik/files/1508184/config.log)

PS : There are also a lot of dependencies that have to be installed by hand after seeing the compilation errors, I don't know anything in this domain, but couldn't they be installed automatically ?

**Comment by ita1024** [comment]
I guess that anaconda3 refers to the rpm package build system?

The config.log mentions that Qt5WebEngineWidgets is not found, so another symlink may be missing or the PKG_CONFIG_PATH variable should be set. Try executing the pkg-config command from anaconda or from the wscript code.

Dependencies for a few systems are described in the README file; they cannot be installed automatically because that is very system-dependent and very dangerous. If you have the list for Fedora please mention it here and I can amend the installation instructions.

**Comment by ita1024** [comment]
Build works for me:
https://github.com/ita1024/semantik/blob/master/README#L15

See also:
https://waf.io/cilog/?jobnum=6&jobname=semantik-fedora

**Comment by ita1024** [comment]
Or https://waf.io/semantik-1.0.1-0.8.fc27.x86_64.rpm (links from the home page)
